### ISSUE TITLE
Version of tensorflow and keras

### ISSUE THREAD

**Issue by salhasalman** [chanchalIITP/AuthorIdentification#1]
Hi
Can I know the version of tensorflow and keras that you  used for the code

**Comment by salhasalman** [comment]
@chanchalIITP 
Hi
Can I know the version of tensorflow and keras that you used for the code

**Comment by chanchalIITP** [comment]
Hello,
Thanks for reaching out. The Tensorflow version is 1.x, and compatible Keras version.
